#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_EXPERIENCE___TESTS___PLUGIN_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_EXPERIENCE___TESTS___PLUGIN_TEST_H
#include "core.hpp"
#include "vitest.hpp"
#include "../src/index.h"

#endif
