#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_AUTOCODER_SRC_PROVIDERS_PROJECTS_PROVIDER_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_AUTOCODER_SRC_PROVIDERS_PROJECTS_PROVIDER_H
#include "core.hpp"
// External dependency removed
#include "../types.h"

extern std::shared_ptr<Provider> projectsProvider;
#endif
