#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_ELIZAOS_SERVICES_SRC___TESTS___INTEGRATION_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_ELIZAOS_SERVICES_SRC___TESTS___INTEGRATION_TEST_H
#include "core.hpp"
#include "bun:test.h"
#include "../index.h"
#include "./test-utils.h"
// External dependency removed

#endif
