#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_PLUGIN_SPECIFICATION_CORE_PLUGIN_V2_SRC_PROMPTS_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_PLUGIN_SPECIFICATION_CORE_PLUGIN_V2_SRC_PROMPTS_H
#include "core.hpp"
// External dependency removed
using coreShouldRespondTemplate = shouldRespondTemplate;
using coreMessageHandlerTemplate = messageHandlerTemplate;
using corePostCreationTemplate = postCreationTemplate;
using coreBooleanFooter = booleanFooter;
using coreImageDescriptionTemplate = imageDescriptionTemplate;

extern string shouldRespondTemplate;
extern string messageHandlerTemplate;
extern string postCreationTemplate;
extern string booleanFooter;
extern string imageDescriptionTemplate;
#endif
