#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_PLUGIN-DUMMY-SERVICES_SRC_WALLET___TESTS___SERVICE_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_PLUGIN-DUMMY-SERVICES_SRC_WALLET___TESTS___SERVICE_TEST_H
#include "core.h"
#include "bun:test.h"
#include "../service.h"
#include "@elizaos/core.h"

#endif
