#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_OTAKU_SRC_PLUGINS_PLUGIN-BOOTSTRAP_SRC_ACTIONS_IGNORE_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_OTAKU_SRC_PLUGINS_PLUGIN-BOOTSTRAP_SRC_ACTIONS_IGNORE_H
#include "core.h"
#include "@elizaos/core.h"

extern std::shared_ptr<Action> ignoreAction;
#endif
