#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_OTC_AGENT_SRC_LIB_PLUGIN_OTC_DESK_PROVIDERS_SHAW_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_OTC_AGENT_SRC_LIB_PLUGIN_OTC_DESK_PROVIDERS_SHAW_H
#include "core.hpp"
// External dependency removed

extern std::shared_ptr<Provider> tokenProvider;
#endif
