#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_OTAKU_SRC_PLUGINS_PLUGIN_GAMIFICATION_SRC_ACTIONS_GETLEADERBOARD_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_OTAKU_SRC_PLUGINS_PLUGIN_GAMIFICATION_SRC_ACTIONS_GETLEADERBOARD_H
#include "core.hpp"
// External dependency removed
#include "../services/GamificationService.h"

extern std::shared_ptr<Action> getLeaderboardAction;
#endif
