#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_GOALS_SRC_TESTS_SCHEMA_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_GOALS_SRC_TESTS_SCHEMA_TEST_H
#include "core.hpp"
#include "bun:test.h"
#include "drizzle-orm.h"
#include "../schema.h"

#endif
