#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_PLUGIN-SQL_SRC___TESTS___UNIT_PGLITE_MANAGER_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_PLUGIN-SQL_SRC___TESTS___UNIT_PGLITE_MANAGER_TEST_H
#include "core.h"
#include "bun:test.h"
#include "../../../pglite/manager.h"

#endif
