#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTO_FUN_PACKAGES_SERVER_SRC_ALLOWEDORIGINS_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTO_FUN_PACKAGES_SERVER_SRC_ALLOWEDORIGINS_H
#include "core.h"

extern array<string> envAllowedOrigins;
extern array<string> allowedOrigins;
#endif
