#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_AGENTSERVER_SRC___TESTS___CAPABILITY-PROGRESSION_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_AGENTSERVER_SRC___TESTS___CAPABILITY-PROGRESSION_TEST_H
#include "core.h"
#include "bun:test.h"
#include "@elizaos/core.h"
#include "../services/capabilityProgressionService.h"

#endif
