#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-PERSONALITY_SRC___TESTS___UNIT_CHARACTER-FILE-MANAGER_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-PERSONALITY_SRC___TESTS___UNIT_CHARACTER-FILE-MANAGER_TEST_H
#include "core.h"
#include "bun:test.h"
#include "../../services/character-file-manager.h"
#include "@elizaos/core.h"

#endif
