#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTO_FUN_PACKAGES_PROGRAM_SCRIPTS_CREATERAYDIUMPOOL_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTO_FUN_PACKAGES_PROGRAM_SCRIPTS_CREATERAYDIUMPOOL_H
#include "core.h"
#include "@coral-xyz/anchor.h"

void main();

#endif
