#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_SPARTAN_SRC_PLUGINS_DEGENINTEL_INTERFACES_INT_USERS_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_SPARTAN_SRC_PLUGINS_DEGENINTEL_INTERFACES_INT_USERS_H
#include "core.h"
#include "@elizaos/core.h"

void interface_list_users(any runtime);

#endif
