#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_PLUGIN-SPECIFICATION_CORE-PLUGIN-V2___TESTS___MOCKCHARACTER_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_PLUGIN-SPECIFICATION_CORE-PLUGIN-V2___TESTS___MOCKCHARACTER_H
#include "core.h"
#include "@elizaos/core.h"

extern std::shared_ptr<Character> mockCharacter;
#endif
