#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_CORE_SRC___TESTS___PROMPTS_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_CORE_SRC___TESTS___PROMPTS_TEST_H
#include "core.h"
#include "bun:test.h"
#include "../prompts.h"

#endif
