#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTOFUN-IDL_TYPES_RAYDIUM_VAULT_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTOFUN-IDL_TYPES_RAYDIUM_VAULT_H
#include "core.h"

typedef object RaydiumVault;


#endif
