#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-EXPERIENCE_SRC_ACTIONS_RECORD-EXPERIENCE_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-EXPERIENCE_SRC_ACTIONS_RECORD-EXPERIENCE_H
#include "core.h"
#include "@elizaos/core.h"

extern std::shared_ptr<Action> recordExperienceAction;
#endif
