#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTONOMOUS-STARTER_SRC_PLUGIN-MANAGER_PROVIDERS_REGISTRYPLUGINSPROVIDER_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTONOMOUS-STARTER_SRC_PLUGIN-MANAGER_PROVIDERS_REGISTRYPLUGINSPROVIDER_H
#include "core.h"
#include "@elizaos/core.h"
#include "../services/pluginManagerService.h"

extern std::shared_ptr<Provider> registryPluginsProvider;
#endif
