#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-GOALS_SRC_TESTS_SCHEMA_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-GOALS_SRC_TESTS_SCHEMA_TEST_H
#include "core.h"
#include "bun:test.h"
#include "drizzle-orm.h"
#include "../schema.h"

#endif
