#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-AUTONOMY_SRC_STATUS-PROVIDER_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-AUTONOMY_SRC_STATUS-PROVIDER_H
#include "core.h"
#include "@elizaos/core.h"

extern std::shared_ptr<Provider> autonomyStatusProvider;
#endif
