#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_DISCRUB-EXT_SRC_TYPES_THREAD-MEMBER-OBJECT_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_DISCRUB-EXT_SRC_TYPES_THREAD-MEMBER-OBJECT_H
#include "core.h"
#include "./guild-member-object.h"

typedef object ThreadMemberObject;


#endif
