#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_THE-ORG_SRC_COMMUNITYMANAGER_PLUGINS_COMMUNITYMANAGER_PROVIDERS_TIMEOUT_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_THE-ORG_SRC_COMMUNITYMANAGER_PLUGINS_COMMUNITYMANAGER_PROVIDERS_TIMEOUT_H
#include "core.h"
#include "@elizaos/core.h"
#include "@elizaos/core.h"

extern std::shared_ptr<Provider> timeoutUserProvider;
#endif
