#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTONOMOUS-STARTER_SRC_PLUGIN-SELF-MODIFICATION_SRC___TESTS___XML-PARSER_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTONOMOUS-STARTER_SRC_PLUGIN-SELF-MODIFICATION_SRC___TESTS___XML-PARSER_TEST_H
#include "core.h"
#include "vitest.h"
#include "../utils/xml-parser.h"
#include "../types.h"

#endif
