#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_CLI_SRC_UTILS_REGISTRY_CONSTANTS_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_CLI_SRC_UTILS_REGISTRY_CONSTANTS_H
#include "core.h"

extern string REGISTRY_ORG;
extern string REGISTRY_REPO_NAME;
extern string REGISTRY_REPO;
extern string REGISTRY_URL;
extern string REGISTRY_GITHUB_URL;
extern string RAW_REGISTRY_URL;
#endif
