#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_CLI_SRC_SCRIPTS_COPY-CLIENT-DIST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_CLI_SRC_SCRIPTS_COPY-CLIENT-DIST_H
#include "core.h"
#include "@/src/utils.h"

void main();

#endif
