#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_DISCRUB_EXT_SRC_TYPES_STICKER_OBJECT_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_DISCRUB_EXT_SRC_TYPES_STICKER_OBJECT_H
#include "core.hpp"
#include "../classes/user.h"

typedef object StickerObject;


#endif
