#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_DISCRUB-EXT_SRC_ENUM_MESSAGE-TYPE_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_DISCRUB-EXT_SRC_ENUM_MESSAGE-TYPE_H
#include "core.h"

enum struct MessageType;

enum struct MessageType {
    DEFAULT = std:("0"), RECIPIENT_ADD = std:("1"), RECIPIENT_REMOVE = std:("2"), CALL = std:("3"), CHANNEL_NAME_CHANGE = std:("4"), CHANNEL_ICON_CHANGE = std:("5"), CHANNEL_PINNED_MESSAGE = std:("6"), USER_JOIN = std:("7"), GUILD_BOOST = std:("8"), GUILD_BOOST_TIER_1 = std:("9"), GUILD_BOOST_TIER_2 = std:("10"), GUILD_BOOST_TIER_3 = std:("11"), CHANNEL_FOLLOW_ADD = std:("12"), GUILD_DISCOVERY_DISQUALIFIED = std:("14"), GUILD_DISCOVERY_REQUALIFIED = std:("15"), GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING = std:("16"), GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING = std:("17"), THREAD_CREATED = std:("18"), REPLY = std:("19"), CHAT_INPUT_COMMAND = std:("20"), THREAD_STARTER_MESSAGE = std:("21"), GUILD_INVITE_REMINDER = std:("22"), CONTEXT_MENU_COMMAND = std:("23"), AUTO_MODERATION_ACTION = std:("24"), ROLE_SUBSCRIPTION_PURCHASE = std:("25"), INTERACTION_PREMIUM_UPSELL = std:("26"), STAGE_START = std:("27"), STAGE_END = std:("28"), STAGE_SPEAKER = std:("29"), STAGE_TOPIC = std:("31"), GUILD_APPLICATION_PREMIUM_SUBSCRIPTION = std:("32")
};
#endif
