#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTO_FUN_PACKAGES_SERVER_SRC_PROMPTS_CREATE-TOKEN_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTO_FUN_PACKAGES_SERVER_SRC_PROMPTS_CREATE-TOKEN_H
#include "core.h"
#include "./constants.h"

any createTokenPrompt(any validatedData = undefined);

#endif
