#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_DISCRUB-EXT_SRC_TYPES_ROLE-SUBSCRIPTION-DATA-OBJECT_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_DISCRUB-EXT_SRC_TYPES_ROLE-SUBSCRIPTION-DATA-OBJECT_H
#include "core.h"

typedef object RoleSubscriptionDataObject;


#endif
