#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_DISCRUB-EXT_SRC_TYPES_TEAM-MEMBER-OBJECT_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_DISCRUB-EXT_SRC_TYPES_TEAM-MEMBER-OBJECT_H
#include "core.h"
#include "../classes/user.h"

typedef object TeamMemberObject;


#endif
