/**
 * Lessons formatting to markdown
 */
import type { LessonsContext } from './lessons-context.js';
import * as Normalize from './lessons-normalize.js';
import { MAX_GLOBAL_LESSONS_FOR_SYNC, MAX_FILE_LESSONS_FOR_SYNC, MAX_FILES_FOR_SYNC } from './lessons-paths.js';

export function collectOrphanLessons(ctx: LessonsContext): string[] {
  const orphans: string[] = [];
  for (const [filePath, lessons] of Object.entries(ctx.store.files)) {
    const cleanedFilePath = Normalize.sanitizeFilePathHeader(filePath);
    for (const lesson of lessons) {
      const normalized = Normalize.normalizeLessonText(lesson);
      if (!normalized) continue;
      const lessonFilePath = Normalize.extractLessonFilePath(normalized);
      const cleanedLessonPath = lessonFilePath ? Normalize.sanitizeFilePathHeader(lessonFilePath) : null;
      if (!cleanedLessonPath || cleanedLessonPath !== cleanedFilePath) {
        orphans.push(normalized);
      }
    }
  }
  return orphans;
}

export function getMergedFileEntries(ctx: LessonsContext): Array<{ filePath: string; lessons: string[]; order: number }> {
  const merged = new Map<string, { lessons: string[]; seen: Set<string>; order: number }>();
  let order = 0;

  for (const [filePath, lessons] of Object.entries(ctx.store.files)) {
    const cleanedPath = Normalize.sanitizeFilePathHeader(filePath);
    if (!cleanedPath) continue;
    
    if (!merged.has(cleanedPath)) {
      merged.set(cleanedPath, {
        lessons: [],
        seen: new Set(),
        order: order++,
      });
    }
    
    const entry = merged.get(cleanedPath)!;
    for (const lesson of lessons) {
      const normalized = Normalize.normalizeLessonText(lesson);
      if (!normalized) continue;
      const lessonFilePath = Normalize.extractLessonFilePath(normalized);
      const cleanedLessonPath = lessonFilePath ? Normalize.sanitizeFilePathHeader(lessonFilePath) : null;
      if (!cleanedLessonPath || cleanedLessonPath !== cleanedPath) {
        continue;
      }
      const key = Normalize.lessonKey(normalized);
      const nearKey = Normalize.lessonNearKey(normalized);
      if (entry.seen.has(key) || entry.seen.has(nearKey)) continue;
      entry.seen.add(key);
      entry.seen.add(nearKey);
      entry.lessons.push(normalized);
    }
  }
  
  return Array.from(merged.entries())
    .map(([filePath, data]) => ({
      filePath,
      lessons: data.lessons,
      order: data.order,
    }))
    .filter(entry => entry.lessons.length > 0)
    .sort((a, b) => a.order - b.order);
}

export function toMarkdown(ctx: LessonsContext): string {
  const lines: string[] = [
    '# PRR Lessons Learned',
    '',
    '> This file is auto-generated by [prr](https://github.com/elizaOS/prr).',
    '> It contains lessons learned from PR review fixes to help improve future fix attempts.',
    '> You can edit this file manually or let prr update it.',
    '> To share lessons across your team, commit this file to your repo.',
    '',
  ];

  const globalLessons = Normalize.sanitizeLessonsList([...ctx.store.global, ...collectOrphanLessons(ctx)]);
  if (globalLessons.length > 0) {
    lines.push('## Global Lessons');
    lines.push('');
    for (const lesson of globalLessons) {
      lines.push(`- ${lesson}`);
    }
    lines.push('');
  }

  const fileEntries = getMergedFileEntries(ctx).map(entry => [entry.filePath, entry.lessons] as const);
  if (fileEntries.length > 0) {
    lines.push('## File-Specific Lessons');
    lines.push('');

    for (const [filePath, lessons] of fileEntries) {
      lines.push(`### ${filePath}`);
      lines.push('');
      for (const lesson of lessons) {
        lines.push(`- ${lesson}`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

export function toCompactedMarkdown(ctx: LessonsContext): string {
  const lines: string[] = [
    '## PRR Lessons Learned',
    '',
    '> Auto-synced from `.prr/lessons.md` - edit there for full history.',
    '',
  ];

  // Sanitize lessons before syncing to CLAUDE.md
  const globalLessons = Normalize.sanitizeLessonsList([...ctx.store.global, ...collectOrphanLessons(ctx)]);
  const topGlobal = globalLessons.slice(-MAX_GLOBAL_LESSONS_FOR_SYNC);

  if (topGlobal.length > 0) {
    lines.push('### Global');
    lines.push('');
    for (const lesson of topGlobal) {
      const formatted = Normalize.formatLessonForDisplay(lesson);
      lines.push(`- ${formatted}`);
    }
    if (globalLessons.length > MAX_GLOBAL_LESSONS_FOR_SYNC) {
      const remaining = globalLessons.length - MAX_GLOBAL_LESSONS_FOR_SYNC;
      lines.push(`- _(${remaining} more in .prr/lessons.md)_`);
    }
    lines.push('');
  }

  const mergedEntries = getMergedFileEntries(ctx);
  const fileEntries = mergedEntries
    .map(e => ({ ...e, totalLessons: e.lessons.length, lessons: e.lessons.slice(-MAX_FILE_LESSONS_FOR_SYNC) }))
    .filter(e => e.lessons.length > 0)
    .slice(-MAX_FILES_FOR_SYNC);

  if (fileEntries.length > 0) {
    lines.push('### By File');
    lines.push('');

    for (const { filePath, lessons, totalLessons } of fileEntries) {
      lines.push(`**${filePath}**`);
      for (const lesson of lessons) {
        const formatted = Normalize.formatLessonForDisplay(lesson);
        lines.push(`- ${formatted}`);
      }
      if (totalLessons > MAX_FILE_LESSONS_FOR_SYNC) {
        const remaining = totalLessons - MAX_FILE_LESSONS_FOR_SYNC;
        lines.push(`- _(${remaining} more in .prr/lessons.md)_`);
      }
    }

    const totalFiles = mergedEntries.length;
    if (totalFiles > MAX_FILES_FOR_SYNC) {
      const remaining = totalFiles - MAX_FILES_FOR_SYNC;
      lines.push('');
      lines.push(`_(${remaining} more files in .prr/lessons.md)_`);
    }
  }

  return lines.join('\n');
}
