#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_LOCAL_EMBEDDING_VITEST_CONFIG_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_LOCAL_EMBEDDING_VITEST_CONFIG_H
#include "core.hpp"
#include "vitest/config.h"
#include "path.hpp"
// Using alias removed (invalid transpilation)

#endif
