#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_AGENTSERVER_SRC___TESTS___SIMPLE_COMPATIBILITY_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_AGENTSERVER_SRC___TESTS___SIMPLE_COMPATIBILITY_TEST_H
#include "core.hpp"
#include "bun:test.h"
#include "node:path.h"
// Using alias removed (invalid transpilation)

#endif
