#include "/home/runner/work/elizaos-cpp/elizaos-cpp/auto.fun/packages/docs/sidebars.h"

std::shared_ptr<SidebarsConfig> sidebars = object{
    object::pair{std::string("docs"), array<object>{ object{
        object::pair{std::string("type"), std::string("autogenerated")}, 
        object::pair{std::string("dirName"), std::string(".")}
    } }}, 
    object::pair{std::string("api"), array<object>{ object{
        object::pair{std::string("type"), std::string("autogenerated")}, 
        object::pair{std::string("dirName"), std::string(".")}
    } }}
};

void Main(void)
{
}

MAIN
