#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-AUTOCODER_PROJECT-TEMPLATE_SRC_TESTS_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-AUTOCODER_PROJECT-TEMPLATE_SRC_TESTS_H
#include "core.h"

extern array<any> tests;
#endif
