#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_PLUGIN_SPECIFICATION_CORE_PLUGIN_V2___TESTS___ENTITIES_EXTRA_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_PLUGIN_SPECIFICATION_CORE_PLUGIN_V2___TESTS___ENTITIES_EXTRA_TEST_H
#include "core.hpp"
#include "vitest.hpp"
#include "../src/entities.h"
#include "../src.h"

#endif
