#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_PLUGIN_SPECIFICATION_CORE_PLUGIN_V2___TESTS___SEARCH_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_PLUGIN_SPECIFICATION_CORE_PLUGIN_V2___TESTS___SEARCH_TEST_H
#include "core.hpp"
#include "vitest.hpp"
#include "../src/search.h"

#endif
