#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_GAME_CYPRESS_SUPPORT_WAIT_FOR_SERVER_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_GAME_CYPRESS_SUPPORT_WAIT_FOR_SERVER_H
#include "core.hpp"

extern std::function<any(double)> waitForElizaServer;
extern std::function<any(double)> waitForElizaServerOptional;
#endif
