#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_SPARTAN_SRC_PLUGINS_AUTOFUNTRADER_CONFIG_CONFIG_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_SPARTAN_SRC_PLUGINS_AUTOFUNTRADER_CONFIG_CONFIG_H
#include "core.h"

extern object PROVIDER_CONFIG;
extern object CHAIN_CONFIG;
extern object BASE_CONFIG;
extern object ZEROEX_CONFIG;
extern object REQUIRED_SETTINGS;
extern object DEFAULT_CONFIG;
extern object SAFETY_LIMITS;
#endif
