#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-AUTOCODER_SRC___TESTS___AUTOCODER-AGENT_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-AUTOCODER_SRC___TESTS___AUTOCODER-AGENT_TEST_H
#include "core.h"
#include "bun:test.h"
#include "@elizaos/core.h"
#include "uuid.h"
using uuidv4 = v4;

#endif
