#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_OTAKU_SRC_PLUGINS_PLUGIN_GAMIFICATION_SRC_PROVIDERS_POINTSPROVIDER_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_OTAKU_SRC_PLUGINS_PLUGIN_GAMIFICATION_SRC_PROVIDERS_POINTSPROVIDER_H
#include "core.hpp"
// External dependency removed
#include "../services/GamificationService.h"

extern std::shared_ptr<Provider> pointsProvider;
#endif
