#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZA_PACKAGES_CORE_SRC_PROMPTS_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZA_PACKAGES_CORE_SRC_PROMPTS_H
#include "core.hpp"

extern string shouldRespondTemplate;
extern string messageHandlerTemplate;
extern string postCreationTemplate;
extern string booleanFooter;
extern string imageDescriptionTemplate;
#endif
