#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZA_PACKAGES_CORE_SRC_SPECS_V2___TESTS___MOCKCHARACTER_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZA_PACKAGES_CORE_SRC_SPECS_V2___TESTS___MOCKCHARACTER_H
#include "core.hpp"
// External dependency removed

extern std::shared_ptr<Character> mockCharacter;
#endif
