#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-EXPERIENCE___TESTS___PLUGIN_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-EXPERIENCE___TESTS___PLUGIN_TEST_H
#include "core.h"
#include "vitest.h"
#include "../src/index.h"

#endif
