#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_AUTOCODER_SRC___TESTS___AUTOCODER_AGENT_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_AUTOCODER_SRC___TESTS___AUTOCODER_AGENT_TEST_H
#include "core.hpp"
#include "bun:test.h"
// External dependency removed
#include "uuid.hpp"
using uuidv4 = v4;

#endif
