#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_PERSONALITY_SRC___TESTS___UNIT_CHARACTER_FILE_MANAGER_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_PERSONALITY_SRC___TESTS___UNIT_CHARACTER_FILE_MANAGER_TEST_H
#include "core.hpp"
#include "bun:test.h"
#include "../../services/character-file-manager.h"
// External dependency removed

#endif
