#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTONOMOUS-STARTER_SRC_PLUGIN-ENV_GENERATION_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTONOMOUS-STARTER_SRC_PLUGIN-ENV_GENERATION_TEST_H
#include "core.h"
#include "vitest.h"
#include "./generation.h"
#include "@elizaos/core.h"

#endif
