#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_STAGEHAND_SRC___TESTS___SIMPLE_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_STAGEHAND_SRC___TESTS___SIMPLE_TEST_H
#include "core.hpp"
#include "bun:test.h"
#include "../index.h"
#include "../service.h"

#endif
