#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZA_PACKAGES_CLI_TESTS_INTEGRATION_SQL_PLUGIN_EXCLUSION_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZA_PACKAGES_CLI_TESTS_INTEGRATION_SQL_PLUGIN_EXCLUSION_TEST_H
#include "core.hpp"
#include "bun:test.h"
#include "../../src/utils/test-runner.h"
// External dependency removed

#endif
