#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZA_PACKAGES_PLUGIN_SQL_SRC_SCHEMA_CHANNELPARTICIPANT_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZA_PACKAGES_PLUGIN_SQL_SRC_SCHEMA_CHANNELPARTICIPANT_H
#include "core.hpp"
#include "drizzle-orm/pg-core.h"
#include "./channel.h"

extern any channelParticipantsTable;
#endif
