#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_PLUGIN-SQL_SRC_SCHEMA_CHANNELPARTICIPANT_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_PLUGIN-SQL_SRC_SCHEMA_CHANNELPARTICIPANT_H
#include "core.h"
#include "drizzle-orm/pg-core.h"
#include "./channel.h"

extern any channelParticipantsTable;
#endif
