#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-STAGEHAND_SRC___TESTS___SIMPLE_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-STAGEHAND_SRC___TESTS___SIMPLE_TEST_H
#include "core.h"
#include "bun:test.h"
#include "../index.h"
#include "../service.h"

#endif
