#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_AUTONOMOUS_STARTER_SRC_PLUGIN_BOOTSTRAP_PROVIDERS_CAPABILITIES_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_AUTONOMOUS_STARTER_SRC_PLUGIN_BOOTSTRAP_PROVIDERS_CAPABILITIES_H
#include "core.hpp"
// External dependency removed
// External dependency removed

extern std::shared_ptr<Provider> capabilitiesProvider;
#endif
