#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_OTAKU_SRC_PLUGINS_PLUGIN-GAMIFICATION_SRC_CONSTANTS_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_OTAKU_SRC_PLUGINS_PLUGIN-GAMIFICATION_SRC_CONSTANTS_H
#include "core.h"

enum struct GamificationEventType;

enum struct GamificationEventType {
    ACCOUNT_CREATION = std:("ACCOUNT_CREATION"), DAILY_LOGIN_STREAK = std:("DAILY_LOGIN_STREAK"), MEANINGFUL_CHAT = std:("MEANINGFUL_CHAT"), SWAP_COMPLETED = std:("SWAP_COMPLETED"), BRIDGE_COMPLETED = std:("BRIDGE_COMPLETED"), TRANSFER_COMPLETED = std:("TRANSFER_COMPLETED"), DAILY_QUEST = std:("DAILY_QUEST"), REFERRAL_SIGNUP = std:("REFERRAL_SIGNUP"), REFERRAL_ACTIVATION = std:("REFERRAL_ACTIVATION"), REFERRED_WELCOME = std:("REFERRED_WELCOME"), FIRST_CHAIN_BONUS = std:("FIRST_CHAIN_BONUS"), AGENT_ACTION = std:("AGENT_ACTION")
};
extern Record<GamificationEventType, double> BASE_POINTS;
extern Partial<Record<GamificationEventType, double>> DAILY_CAPS;
extern object VOLUME_MULTIPLIERS;
extern array<object> LEVEL_THRESHOLDS;
extern double STREAK_BONUS_PER_DAY;
extern double MAX_STREAK_BONUS;
extern double MIN_TRANSFER_VALUE_USD;
extern double MIN_CHAT_LENGTH;
extern array<object> MESSAGE_LENGTH_TIERS;
extern double DAILY_QUEST_UNIQUE_ACTIONS_REQUIRED;
extern double REFERRAL_ACTIVATION_WINDOW_DAYS;
#endif
