#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-OLLAMA_SRC_INDEX_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-OLLAMA_SRC_INDEX_TEST_H
#include "core.h"
#include "bun:test.h"
#include "./index.h"

#endif
