#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_SPARTAN_SRC_PLUGINS_COMMUNITYINVESTOR_CONSTANTS_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_SPARTAN_SRC_PLUGINS_COMMUNITYINVESTOR_CONSTANTS_H
#include "core.h"

extern double SOLANA_NETWORK_ID;
extern string SOL_ADDRESS;
extern string USDC_ADDRESS;
extern string BTC_ADDRESS;
extern string ETH_ADDRESS;
extern string TRUST_LEADERBOARD_WORLD_SEED;
#endif
