#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-AUTOCODER_PROJECT-TEMPLATE_CYPRESS_CONFIG_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-AUTOCODER_PROJECT-TEMPLATE_CYPRESS_CONFIG_H
#include "core.h"
#include "cypress.h"
#include "./vite.config.h"
using viteConfig = _default;

#endif
