#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_BOOTSTRAP_SRC_PROVIDERS_CAPABILITIES_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_BOOTSTRAP_SRC_PROVIDERS_CAPABILITIES_H
#include "core.hpp"
// External dependency removed
// External dependency removed

extern std::shared_ptr<Provider> capabilitiesProvider;
#endif
