#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_HAT_SRC_SETUPTESTS_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_HAT_SRC_SETUPTESTS_H
#include "core.hpp"
// External dependency removed

#endif
