#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_TODO_SRC_TESTS_PLUGIN_INIT_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_TODO_SRC_TESTS_PLUGIN_INIT_TEST_H
#include "core.hpp"
#include "bun:test.h"
#include "../index.h"
// External dependency removed

#endif
