#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-TODO_SRC_TESTS_PLUGIN-INIT_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-TODO_SRC_TESTS_PLUGIN-INIT_TEST_H
#include "core.h"
#include "bun:test.h"
#include "../index.h"
#include "@elizaos/core.h"

#endif
