#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_SPARTAN_SRC_PLUGINS_PLUGIN-BIRDEYE_SRC_CONSTANTS_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_SPARTAN_SRC_PLUGINS_PLUGIN-BIRDEYE_SRC_CONSTANTS_H
#include "core.h"

extern double DEFAULT_MAX_RETRIES;
extern string BIRDEYE_SERVICE_NAME;
extern object DEFAULT_SUPPORTED_SYMBOLS;
extern string API_BASE_URL;
extern double RETRY_DELAY_MS;
extern object BIRDEYE_ENDPOINTS;
#endif
