#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-STARTER_SRC_ACTIONS_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-STARTER_SRC_ACTIONS_H
#include "core.h"
#include "@elizaos/core.h"

extern array<any> Actions;
#endif
