#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_CORE_SRC___TESTS___MOCKCHARACTER_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_CORE_SRC___TESTS___MOCKCHARACTER_H
#include "core.hpp"
// External dependency removed

extern std::shared_ptr<Character> mockCharacter;
#endif
