#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_OLLAMA_SRC_INDEX_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_OLLAMA_SRC_INDEX_TEST_H
#include "core.hpp"
#include "bun:test.h"
#include "./index.h"

#endif
