#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-AUTOCODER_PROJECT-TEMPLATE_SRC_CHARACTER_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-AUTOCODER_PROJECT-TEMPLATE_SRC_CHARACTER_H
#include "core.h"
#include "@elizaos/core.h"

extern std::shared_ptr<Character> character;
#endif
