#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_SPARTAN_SRC_PLUGINS_AUTOFUNTRADER_UTILS_VALIDATOR_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_SPARTAN_SRC_PLUGINS_AUTOFUNTRADER_UTILS_VALIDATOR_H
#include "core.hpp"
// External dependency removed
// External dependency removed

boolean validateSolanaAddress(any address);

#endif
