#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTOFUN-IDL_TYPES_AUTOFUN_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTOFUN-IDL_TYPES_AUTOFUN_H
#include "core.h"

typedef object Autofun;


#endif
