#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTO_FUN_PACKAGES_AUTODOC_SRC_UTILS_PROMPTS_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTO_FUN_PACKAGES_AUTODOC_SRC_UTILS_PROMPTS_H
#include "core.h"
#include "../AIService/types.h"

extern object PROMPT_TEMPLATES;
#endif
