#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTONOMOUS-STARTER_SRC_PLUGIN-BOOTSTRAP_ACTIONS_NONE_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_AUTONOMOUS-STARTER_SRC_PLUGIN-BOOTSTRAP_ACTIONS_NONE_H
#include "core.h"
#include "@elizaos/core.h"

extern std::shared_ptr<Action> noneAction;
#endif
