#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZAOS_GITHUB_IO_SRC_LIB_FORMAT_NUMBER_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZAOS_GITHUB_IO_SRC_LIB_FORMAT_NUMBER_H
#include "core.hpp"

string formatCompactNumber(double number, double maximumFractionDigits = 1);

#endif
