#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_AUTOCODER_SCRIPTS_DEMO_INTERACTIVE_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_AUTOCODER_SCRIPTS_DEMO_INTERACTIVE_H
#include "core.hpp"
#include "../src/interactive-test.h"

void runDemo();

#endif
