#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_AUTONOMOUS_STARTER_SRC_PLUGIN_SELF_MODIFICATION_SRC___TESTS___CHARACTER_UPDATER_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_AUTONOMOUS_STARTER_SRC_PLUGIN_SELF_MODIFICATION_SRC___TESTS___CHARACTER_UPDATER_TEST_H
#include "core.hpp"
#include "vitest.hpp"
#include "../utils/character-updater.h"
#include "../types.h"

#endif
