#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>
#pragma once

namespace elizaos {

// NOTE: This is auto-generated approximate C++ code
// Manual refinement required for production use

;
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
  title: 'Auto.fun API Documentation',
  tagline: 'Press the fun button',
  favicon: 'img/favicon.ico',

  // Set the production url of your site here
  url: 'https://docs.auto.fun',
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: '/',

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: 'auto.fun', // Usually your GitHub org/user name.
  projectName: 'docs', // Usually your repo name.

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    mermaid: true,
  },

  themes: ['@docusaurus/theme-mermaid'],
  
  plugins: [
    require.resolve('docusaurus-lunr-search'),
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'api',
        path: 'api',
        // Use Docusaurus autogenerated sidebar
        sidebarItemsGenerator: async function({defaultSidebarItemsGenerator, ...args}) {
          return [
            {
              type: 'autogenerated',
              dirName: '.', // Autogenerate sidebar from the root of the 'api' docs folder
            },
          ];
        },
        routeBasePath: 'api',
      },
    ],
    [
      'docusaurus-plugin-typedoc',
      {
        entryPoints: ['../src/components/**/*.tsx', '../src/hooks/**/*.ts', '../src/utils/**/*.ts', '../worker/**/*.ts'],
        tsconfig: '../../tsconfig.json',
        out: './api',
        skipErrorChecking: true,
        excludeExternals: true,
        excludePrivate: true,
        excludeProtected: true,
        excludeInternal: true,
        excludeNotDocumented: true,
        plugin: ['typedoc-plugin-markdown'],
        hideGenerator: true,
        cleanOutputDir: true,
        categorizeByGroup: true,
        pretty: true,
        includeVersion: true,
        sort: ['source-order'],
        gitRevision: 'main',
        readme: 'none',
        commentStyle: 'block',
        preserveAnchorCasing: true,
        hideBreadcrumbs: false,
        preserveWatchOutput: true,
        disableSources: true,
        validation: {
          notExported: false,
          invalidLink: true,
          notDocumented: false
        },
        exclude: [
          '**/_media/**',
          '**/node_modules/**',
          '**/dist/**',
          '**/*.test.ts',
          '**/*.spec.ts',
          '**/*.d.ts',
          '**/index.ts',
        ],
        watch: false,
        treatWarningsAsErrors: false,
        treatValidationWarningsAsErrors: false,
        searchInComments: false,
        navigationLinks: {
          GitHub: 'https://github.com/auto.fun/docs',
          Documentation: '/docs/intro',
        }
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          // Use autogenerated sidebar for main docs
          sidebarItemsGenerator: async function({defaultSidebarItemsGenerator, ...args}) {
            return [
              {
                type: 'autogenerated',
                dirName: '.', // Autogenerate sidebar from the root of the docs folder
              },
            ];
          },
          editUrl: 'https://github.com/auto.fun/docs/tree/main/',
        },
        blog: {
          showReadingTime: true,
          editUrl: 'https://github.com/auto.fun/docs/tree/main/',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      },
    ],
  ],

  themeConfig: {
    // Replace with your project's social card
    image: 'img/social-card.jpg',
    navbar: {
      title: 'Auto.fun API',
      logo: {
        alt: 'Auto.fun Logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'api',
          position: 'left',
          label: 'API',
        },
        {
          href: 'https://github.com/auto.fun/docs',
          label: 'GitHub',
          position: 'right',
        },
        {
          href: 'https://auto.fun',
          label: 'Website',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Getting Started',
              to: '/docs/intro',
            },
            {
              label: 'API Reference',
              to: '/api',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'Discord',
              href: 'https://discord.gg/ai16z',
            },
            {
              label: 'Twitter',
              href: 'https://twitter.com/autodotfun',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/auto.fun',
            },
            {
              label: 'Website',
              href: 'https://auto.fun',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Auto.fun. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  },
};

default config;

} // namespace elizaos
