#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>
#pragma once

namespace elizaos {

// NOTE: This is auto-generated approximate C++ code
// Manual refinement required for production use

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // Autogenerate sidebar from the root of the docs folder
    },
  ],
  
  // API documentation sidebar
  api: [
    {
      type: 'autogenerated',
      dirName: '.', // Autogenerate sidebar from the root of the api folder
    },
  ],
};

default sidebars; 
} // namespace elizaos
