#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_PLUGIN-DUMMY-SERVICES_TSUP_CONFIG_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_PLUGIN-DUMMY-SERVICES_TSUP_CONFIG_H
#include "core.h"
#include "tsup.h"

#endif
