#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_AUTONOMOUS_STARTER_SRC_PLUGIN_EXPERIENCE_UTILS_EXPERIENCETEXTPARSER_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_AUTONOMOUS_STARTER_SRC_PLUGIN_EXPERIENCE_UTILS_EXPERIENCETEXTPARSER_H
#include "core.hpp"
#include <string>

string detectDomain(string text, string defaultDomain = std::string("general"));

#endif
