#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-ELIZAOS-SERVICES_SRC_TESTS_REAL-INTEGRATION_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-ELIZAOS-SERVICES_SRC_TESTS_REAL-INTEGRATION_TEST_H
#include "core.h"
#include "@elizaos/core.h"
#include "@elizaos/core.h"
#include "dotenv.h"

extern object RealIntegrationTestSuite;
#endif
