#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-SQL_SRC___TESTS___UNIT_PG_ADAPTER_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_PLUGIN-SQL_SRC___TESTS___UNIT_PG_ADAPTER_TEST_H
#include "core.h"
#include "bun:test.h"
#include "../../../pg/adapter.h"
#include "@elizaos/core.h"

#endif
