#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZA_PACKAGES_PLUGIN_DUMMY_SERVICES_SRC_TOKENDATA___TESTS___SERVICE_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_ELIZA_PACKAGES_PLUGIN_DUMMY_SERVICES_SRC_TOKENDATA___TESTS___SERVICE_TEST_H
#include "core.hpp"
#include "bun:test.h"
#include "../service.h"
// External dependency removed

#endif
