#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_SPARTAN_SRC_PLUGINS_PLUGIN_COINMARKETCAP_SRC_ACTIONS_GETPRICE_VALIDATION_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_SPARTAN_SRC_PLUGINS_PLUGIN_COINMARKETCAP_SRC_ACTIONS_GETPRICE_VALIDATION_H
#include "core.hpp"
#include "zod.hpp"
#include "./types.h"

extern any GetPriceSchema;
any isGetPriceContent(std::shared_ptr<GetPriceContent> content);

#endif
