#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_DOCS_VERSIONED_DOCS_VERSION-0_25_9_REST_SIDEBAR_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_ELIZA_PACKAGES_DOCS_VERSIONED_DOCS_VERSION-0_25_9_REST_SIDEBAR_H
#include "core.h"
#include "@docusaurus/plugin-content-docs.h"

extern std::shared_ptr<SidebarsConfig> sidebar;
#endif
