#include "sidebars.hpp"

std::shared_ptr<SidebarsConfig> sidebars = object{
    object::pair{std:("docs"), array<object>{ object{
        object::pair{std:("type"), std:("autogenerated")}, 
        object::pair{std:("dirName"), std:(".")}
    } }}, 
    object::pair{std:("api"), array<object>{ object{
        object::pair{std:("type"), std:("autogenerated")}, 
        object::pair{std:("dirName"), std:(".")}
    } }}
};

void Main(void)
{
}

MAIN
