#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_AUTOCODER_PROJECT_TEMPLATE_CYPRESS_CONFIG_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_CLASSIFIED_PACKAGES_PLUGIN_AUTOCODER_PROJECT_TEMPLATE_CYPRESS_CONFIG_H
#include "core.hpp"
// Self-include removed: cypress.hpp
#include "./vite.config.h"
// Using alias removed (invalid transpilation)

#endif
