#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_AUTONOMOUS_STARTER_SRC_PLUGIN_MANAGER_ACTIONS_INSTALLPLUGINFROMREGISTRY_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_AUTONOMOUS_STARTER_SRC_PLUGIN_MANAGER_ACTIONS_INSTALLPLUGINFROMREGISTRY_H
#include "core.hpp"
// External dependency removed
#include "../services/pluginManagerService.h"

extern std::shared_ptr<Action> installPluginFromRegistryAction;
#endif
