#ifndef _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_CORE_SRC_TEST_RESOURCES_CONSTANTS_H
#define _HOME_RUNNER_WORK_ELIZAOS-CPP_ELIZAOS-CPP_CLASSIFIED_PACKAGES_CORE_SRC_TEST_RESOURCES_CONSTANTS_H
#include "core.h"
#include "@elizaos/core.h"

extern string SERVER_URL;
extern string SUPABASE_URL;
extern string SUPABASE_ANON_KEY;
extern string TEST_EMAIL;
extern string TEST_PASSWORD;
extern string TEST_EMAIL_2;
extern string TEST_PASSWORD_2;
extern any zeroUuid;
#endif
