#ifndef _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_AUTONOMOUS_STARTER_SRC_PLUGIN_TODO_TESTS_REMINDERSERVICE_TEST_H
#define _HOME_RUNNER_WORK_ELIZAOS_CPP_ELIZAOS_CPP_AUTONOMOUS_STARTER_SRC_PLUGIN_TODO_TESTS_REMINDERSERVICE_TEST_H
#include "core.hpp"
#include "vitest.hpp"
#include "../reminderService.h"
// External dependency removed

#endif
